[tool.pytest.ini_options]
markers = [
        "online: Tests that require an up and running infrastructure and uploaded model",
        "offlinedata",
        "offlinenodata"
]

[tool.isort]
profile="black"
