name: CI tests
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13
      - name: Install Dependencies
        run: pip install pipenv && pipenv install --dev --python 3.9.13

      - name: Run tests
        run: |
          pipenv run pytest -m offlinenodata
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2

      - name: Setup credentials
        run: |
          echo  '${{ secrets.GCP_TERRAFORM_CREDENTIALS }}' > infrastructure/terraform-account.json
      - name: TF init
        id: plan
        working-directory: "infrastructure"
        run: |
          terraform init -backend-config="prefix="tfstate-prod""
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_CREDENTIALS}}
      - name: TF plan
        id: plan
        run: |
          make plan-prod
